
import { type DayItinerary } from './types';

export const COLORS = {
  preference: '#9DB2D0',
  physical: '#F4A442',
  mental: '#D66D67',
  outline: '#E5E7EB',
  text: '#4B5563',
  costFill: '#ffe796',
  star: '#FFB800',
  transport: '#A5B4FC',
  timelineSpot: '#64748b',
  timelineDot: '#3b82f6'
};

export const ALL_ITINERARIES: DayItinerary[] = [
  {
    "id": 1,
    "timestamp": "2026/1/8 上午2:45:51",
    "result": [
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "安平古堡",
        "Address": "708台南市安平區國勝路82號",
        "Latitude": 23.0016115,
        "Longitude": 120.1605683,
        "SpotType": ["古蹟", "文化"],
        "Description": "台灣最古老的城堡，見證了台南數百年的歷史變遷。",
        "Phone": "06-226-7348",
        "Website": "",
        "StartTime": "09:00",
        "EndTime": "10:30",
        "Rating": 4.2,
        "Cost": 70,
        "WalkingLoad": 6,
        "InfoLoad": 7,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "步行",
        "Distance": "0.5 km",
        "Duration": "10 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "安平樹屋",
        "Address": "708台南市安平區古堡街108號",
        "Latitude": 23.0040326,
        "Longitude": 120.1597397,
        "SpotType": ["古蹟", "風景", "文化"],
        "Description": "原為英商德記洋行倉庫，後因榕樹盤根錯節，與建築共生。",
        "Phone": "+886 06 391 3901",
        "Website": "",
        "StartTime": "10:40",
        "EndTime": "12:00",
        "Rating": 4.3,
        "Cost": 50,
        "WalkingLoad": 5,
        "InfoLoad": 6,
        "CrowdLevel": 6,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "汽車",
        "Distance": "1.5 km",
        "Duration": "5 min",
        "Speed": "20 km/h",
        "Cost": 50
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "周氏蝦捲",
        "Address": "708台南市安平區安平路408-1號",
        "Latitude": 22.9998218,
        "Longitude": 120.1631901,
        "SpotType": ["美食"],
        "Description": "台南安平區的經典小吃，以新鮮蝦仁製作。",
        "Phone": "06-280-1304",
        "Website": "",
        "StartTime": "12:05",
        "EndTime": "13:00",
        "Rating": 4.1,
        "Cost": 200,
        "WalkingLoad": 2,
        "InfoLoad": 2,
        "CrowdLevel": 8,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 23
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "汽車",
        "Distance": "4.5 km",
        "Duration": "15 min",
        "Speed": "18 km/h",
        "Cost": 150
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "赤崁樓",
        "Address": "700台南市中西區民族路二段212號",
        "Latitude": 22.9972744,
        "Longitude": 120.2027032,
        "SpotType": ["古蹟", "文化"],
        "Description": "台南市區的代表性古蹟，曾是荷蘭人的普羅民遮城。",
        "Phone": "+886 6 220 5647",
        "Website": "",
        "StartTime": "13:15",
        "EndTime": "15:00",
        "Rating": 4.4,
        "Cost": 70,
        "WalkingLoad": 6,
        "InfoLoad": 7,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 24
      }
    ]
  },
  {
    "id": 2,
    "timestamp": "2026/1/8 上午2:52:19",
    "result": [
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "赤崁樓",
        "Address": "700台南市中西區民族路二段212號",
        "Latitude": 22.9972744,
        "Longitude": 120.2027032,
        "SpotType": ["古蹟", "文化"],
        "Description": "台南市最著名的歷史古蹟之一，前身為荷蘭人所建普羅民遮城。",
        "Phone": "+886 6 220 5647",
        "Website": "",
        "StartTime": "09:00",
        "EndTime": "10:30",
        "Rating": 4.4,
        "Cost": 50,
        "WalkingLoad": 6,
        "InfoLoad": 8,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 23
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "步行",
        "Distance": "0.4 km",
        "Duration": "5 min",
        "Speed": "4.8 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "度小月擔仔麵 (赤崁店)",
        "Address": "700台南市中西區民族路二段216號",
        "Latitude": 22.9923208,
        "Longitude": 120.2037117,
        "SpotType": ["美食"],
        "Description": "傳承百年、聞名國際的台南小吃代表。",
        "Phone": "062231744",
        "Website": "",
        "StartTime": "10:35",
        "EndTime": "11:35",
        "Rating": 4.1,
        "Cost": 200,
        "WalkingLoad": 1,
        "InfoLoad": 2,
        "CrowdLevel": 7,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 24
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "汽車",
        "Distance": "6.5 km",
        "Duration": "18 min",
        "Speed": "21.7 km/h",
        "Cost": 180
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-01-08",
        "SpotName": "安平古堡",
        "Address": "708台南市安平區國勝路82號",
        "Latitude": 23.0016115,
        "Longitude": 120.1605683,
        "SpotType": ["古蹟", "文化", "風景"],
        "Description": "台灣最早的城堡，由荷蘭人興建。",
        "Phone": "062267348",
        "Website": "",
        "StartTime": "14:07",
        "EndTime": "15:45",
        "Rating": 4.3,
        "Cost": 70,
        "WalkingLoad": 7,
        "InfoLoad": 8,
        "CrowdLevel": 7,
        "IndoorOutdoor": "戶外",
        "WeatherType": "晴到多雲",
        "Temperature": 26
      }
    ]
  },
  {
    "id": 3,
    "timestamp": "2026/2/12 上午1:39:55",
    "result": [
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "臺南車站",
        "Address": "台南市東區成功路6號",
        "Latitude": 22.9973597,
        "Longitude": 120.2137846,
        "SpotType": [
          "文化",
          "交通"
        ],
        "Description": "臺南車站是台南市重要的交通樞紐，見證了這座城市的發展與變遷。其建築融合了日式與西式風格，是許多旅人抵達古都的第一站，周邊交通便利，前往各景點都十分便捷。站內外亦有許多商店與美食，可在此稍作休息。",
        "Phone": "06-2001111",
        "Website": "https://www.youbike.com.tw/region/tainan",
        "StartTime": "10:00",
        "EndTime": "10:30",
        "Rating": 3.8,
        "Cost": 0,
        "WalkingLoad": 3,
        "InfoLoad": 2,
        "CrowdLevel": 7,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "汽車",
        "Distance": "2.5 km",
        "Duration": "10 min",
        "Speed": "15 km/h",
        "Cost": 150
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "赤崁樓",
        "Address": "台南市中西區民族路二段212號",
        "Latitude": 22.9972744,
        "Longitude": 120.2027032,
        "SpotType": [
          "古蹟",
          "文化",
          "風景"
        ],
        "Description": "赤崁樓是台南的指標性古蹟，前身為荷蘭人興建的普羅民遮城。歷史悠久，見證了台灣數百年來的政治變遷。園區內保存有石龜碑、斷足石馬等文物，是了解台南歷史的絕佳地點，夜晚燈光照射下更顯其莊嚴與美麗。",
        "Phone": "+886 6 220 5647",
        "Website": "https://historic.tainan.gov.tw/index.php?option=module&lang=en&task=pageinfo&id=189&index=2",
        "StartTime": "10:45",
        "EndTime": "12:15",
        "Rating": 4.5,
        "Cost": 70,
        "WalkingLoad": 6,
        "InfoLoad": 8,
        "CrowdLevel": 7,
        "IndoorOutdoor": "戶外",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "步行",
        "Distance": "0.1 km",
        "Duration": "1 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "度小月擔仔麵 (赤崁店)",
        "Address": "台南市中西區民族路二段216號",
        "Latitude": 22.9923208,
        "Longitude": 120.2037117,
        "SpotType": [
          "美食"
        ],
        "Description": "度小月擔仔麵是台南的百年老店，以其獨特的肉燥和鮮蝦湯頭聞名。小巧的麵碗盛裝著濃郁的湯汁和Q彈的麵條，配上蒜泥和香菜，風味絕佳。是體驗台南傳統小吃文化的必訪之地。",
        "Phone": "06-2234567",
        "Website": "https://www.google.com/search?q=%E5%BA%A6%E5%B0%8F%E6%9C%88%E6%93%94%E4%BB%94%E9%BA%B5%20(%E8%B5%A4%E5%B4%81%E5%BA%97)",
        "StartTime": "12:20",
        "EndTime": "13:20",
        "Rating": 4.2,
        "Cost": 100,
        "WalkingLoad": 1,
        "InfoLoad": 2,
        "CrowdLevel": 8,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "步行",
        "Distance": "0.8 km",
        "Duration": "10 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "臺南孔子廟",
        "Address": "台南市中西區南門路2號",
        "Latitude": 22.9904656,
        "Longitude": 120.2039363,
        "SpotType": [
          "古蹟",
          "文化",
          "宗教"
        ],
        "Description": "臺南孔子廟是全台第一座孔廟，被譽為「全臺首學」。其建築格局莊嚴典雅，是儒家文化的重要象徵。廟內古樹參天，環境清幽，讓人感受到歷史的厚重與文化的薰陶。是沉澱心靈，感受書卷氣息的好地方。",
        "Phone": "06-2245678",
        "Website": "https://www.google.com/search?q=%E8%87%BA%E5%8D%97%E5%AD%94%E5%AD%90%E5%BB%9F",
        "StartTime": "13:30",
        "EndTime": "15:00",
        "Rating": 4.6,
        "Cost": 0,
        "WalkingLoad": 5,
        "InfoLoad": 7,
        "CrowdLevel": 6,
        "IndoorOutdoor": "戶外",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "步行",
        "Distance": "0.1 km",
        "Duration": "2 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "府中街 (孔廟商圈)",
        "Address": "台南市中西區府中街",
        "Latitude": 22.9907419,
        "Longitude": 120.2074983,
        "SpotType": [
          "美食",
          "文化",
          "購物"
        ],
        "Description": "府中街位於孔廟旁，是一條充滿文創氣息的老街。兩旁古色古香的建築裡，進駐了許多特色小店、手作文創商品和風味小吃。漫步其中，品嚐街邊美食，感受悠閒的氛圍，是體驗台南慢活步調的好去處。",
        "Phone": "06-2256789",
        "Website": "https://www.google.com/search?q=%E5%BA%9C%E4%B8%AD%E8%A1%97%20(%E5%AD%94%E5%BB%9F%E5%95%86%E5%9C%88)",
        "StartTime": "15:05",
        "EndTime": "16:30",
        "Rating": 4.3,
        "Cost": 200,
        "WalkingLoad": 6,
        "InfoLoad": 5,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "步行",
        "Distance": "0.2 km",
        "Duration": "3 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "莉莉水果店",
        "Address": "台南市中西區府前路一段199號",
        "Latitude": 22.9890421,
        "Longitude": 120.204062,
        "SpotType": [
          "美食",
          "休閒"
        ],
        "Description": "莉莉水果店是台南的傳奇冰果室，以新鮮水果和自製冰品聞名。多樣的選擇和季節限定的美味，吸引了無數遊客和在地人。在這裡品嚐一碗清涼的水果冰，是夏日消暑，冬日暖心的最佳選擇，感受府城獨有的甜蜜。",
        "Phone": "06-2267890",
        "Website": "https://www.google.com/search?q=%E8%8E%89%E8%8E%89%E6%B0%B4%E6%9E%9C%E5%BA%97",
        "StartTime": "16:35",
        "EndTime": "17:30",
        "Rating": 4.4,
        "Cost": 120,
        "WalkingLoad": 1,
        "InfoLoad": 2,
        "CrowdLevel": 8,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 1,
        "TransportType": "汽車",
        "Distance": "2.0 km",
        "Duration": "8 min",
        "Speed": "15 km/h",
        "Cost": 120
      },
      {
        "DataType": "Spot",
        "Day": 1,
        "Date": "2026-02-12",
        "SpotName": "台南香格里拉遠東國際大飯店",
        "Address": "台南市東區大學路西段89號",
        "Latitude": 22.997,
        "Longitude": 120.2139,
        "SpotType": [
          "住宿"
        ],
        "Description": "台南香格里拉遠東國際大飯店位於市中心，交通便利，是商務與觀光旅客的理想選擇。飯店設施完善，服務親切，房間舒適寬敞，可俯瞰城市美景。鄰近車站，方便前往各景點，為旅途提供舒適的休憩空間。",
        "Phone": "06-7028888",
        "Website": "https://www.shangri-la.com/tainan/fareasternplaza",
        "StartTime": "17:45",
        "EndTime": "24:00",
        "Rating": 4.6,
        "Cost": 3500,
        "WalkingLoad": 2,
        "InfoLoad": 2,
        "CrowdLevel": 5,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": false
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "台南香格里拉遠東國際大飯店",
        "Address": "台南市東區大學路西段89號",
        "Latitude": 22.997,
        "Longitude": 120.2139,
        "SpotType": [
          "住宿"
        ],
        "Description": "在舒適的飯店內享用早餐後，準備展開第二天的台南古蹟美食之旅。飯店提供的多樣餐飲選擇與便利設施，讓旅客能養精蓄銳，以最佳狀態迎接新的探險。此為從飯店出發前往下一個目的地的起點。",
        "Phone": "06-7028888",
        "Website": "https://www.shangri-la.com/tainan/fareasternplaza",
        "StartTime": "00:00",
        "EndTime": "09:00",
        "Rating": 4.6,
        "Cost": 0,
        "WalkingLoad": 1,
        "InfoLoad": 1,
        "CrowdLevel": 3,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": false
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "汽車",
        "Distance": "7.0 km",
        "Duration": "20 min",
        "Speed": "20 km/h",
        "Cost": 250
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "安平樹屋",
        "Address": "台南市安平區古堡街108號",
        "Latitude": 23.0040326,
        "Longitude": 120.1597397,
        "SpotType": [
          "古蹟",
          "風景",
          "文化"
        ],
        "Description": "安平樹屋是一處獨特的歷史建築群，榕樹盤根錯節地包覆著舊倉庫，形成了宛如迷宮般的奇特景觀。這裡是藝術與自然的完美結合，也是攝影愛好者的天堂。漫步其中，感受歷史的滄桑與大自然的鬼斧神工。",
        "Phone": "+886 06 391 3901",
        "Website": "https://www.google.com/search?q=%E5%AE%89%E5%B9%B3%E6%A8%B9%E5%B1%8B",
        "StartTime": "09:20",
        "EndTime": "10:50",
        "Rating": 4.4,
        "Cost": 50,
        "WalkingLoad": 7,
        "InfoLoad": 6,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "步行",
        "Distance": "0.5 km",
        "Duration": "6 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "安平古堡",
        "Address": "台南市安平區國勝路82號",
        "Latitude": 23.0016115,
        "Longitude": 120.1605683,
        "SpotType": [
          "古蹟",
          "文化"
        ],
        "Description": "安平古堡，又稱熱蘭遮城，是台灣最古老的城堡，由荷蘭人興建。登高可俯瞰安平地區風光，感受歷史的厚重。園區內有瞭望台、城牆遺跡及文物陳列，是了解台灣早期歷史的重要據點，也是台南必訪的古蹟之一。",
        "Phone": "06-2267891",
        "Website": "https://www.google.com/search?q=%E5%AE%89%E5%B9%B3%E5%8F%A4%E5%A0%A1",
        "StartTime": "10:55",
        "EndTime": "12:25",
        "Rating": 4.3,
        "Cost": 70,
        "WalkingLoad": 7,
        "InfoLoad": 8,
        "CrowdLevel": 8,
        "IndoorOutdoor": "戶外",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "步行",
        "Distance": "0.3 km",
        "Duration": "4 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "安平老街",
        "Address": "台南市安平區延平街",
        "Latitude": 23.0006699,
        "Longitude": 120.1624005,
        "SpotType": [
          "美食",
          "購物",
          "文化"
        ],
        "Description": "安平老街是台灣最早開發的街道之一，充滿古色古香的氛圍。街上琳瑯滿目的傳統小吃、文創商品和古早味童玩，讓人目不暇給。品嚐蝦餅、蜜餞、蚵仔煎等在地美食，感受濃厚的歷史文化氣息，是體驗台南小吃的好去處。",
        "Phone": "06-2278901",
        "Website": "https://www.google.com/search?q=%E5%AE%89%E5%B9%B3%E8%80%81%E8%A1%97",
        "StartTime": "12:30",
        "EndTime": "14:30",
        "Rating": 4.2,
        "Cost": 300,
        "WalkingLoad": 8,
        "InfoLoad": 6,
        "CrowdLevel": 9,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "汽車",
        "Distance": "7.5 km",
        "Duration": "20 min",
        "Speed": "22 km/h",
        "Cost": 250
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "林百貨",
        "Address": "台南市中西區忠義路二段63號",
        "Latitude": 22.9917101,
        "Longitude": 120.2025267,
        "SpotType": [
          "購物",
          "文化",
          "藝術"
        ],
        "Description": "林百貨是台南重要的歷史建築，曾是日治時期南台灣最高的百貨公司。修復後，保留了當年風華，內部販售文創商品、在地伴手禮，頂樓還有神社。是結合歷史、文創與購物的特色景點，感受台南的懷舊與新意。",
        "Phone": "06-2211212",
        "Website": "http://www.hayashi.com.tw",
        "StartTime": "14:50",
        "EndTime": "16:20",
        "Rating": 4.5,
        "Cost": 0,
        "WalkingLoad": 5,
        "InfoLoad": 7,
        "CrowdLevel": 8,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "步行",
        "Distance": "0.3 km",
        "Duration": "4 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "窄門咖啡",
        "Address": "台南市中西區衛民街1號",
        "Latitude": 22.9896797,
        "Longitude": 120.2048415,
        "SpotType": [
          "休閒",
          "美食"
        ],
        "Description": "窄門咖啡以其獨特的狹窄入口聞名，內部空間卻別有洞天，充滿懷舊氛圍。在這裡可以品嚐咖啡與甜點，享受午後的悠閒時光。是遠離喧囂，尋求片刻寧靜的理想場所，體驗台南巷弄裡的驚喜。",
        "Phone": "06-2289012",
        "Website": "https://www.google.com/search?q=%E7%AA%84%E9%96%80%E5%92%96%E5%95%A1",
        "StartTime": "16:25",
        "EndTime": "17:25",
        "Rating": 4,
        "Cost": 180,
        "WalkingLoad": 2,
        "InfoLoad": 3,
        "CrowdLevel": 6,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "步行",
        "Distance": "0.5 km",
        "Duration": "6 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "大天后宮",
        "Address": "台南市中西區永福路二段227巷18號",
        "Latitude": 22.996518,
        "Longitude": 120.2017095,
        "SpotType": [
          "宗教",
          "古蹟"
        ],
        "Description": "大天后宮是台灣第一座官建媽祖廟，歷史悠久，雕樑畫棟，氣勢恢宏。廟宇內收藏了許多珍貴的歷史文物，是研究台灣宗教與建築藝術的重要場所。來此感受媽祖信仰的莊嚴與信眾的虔誠，體驗傳統文化。",
        "Phone": "06-2290123",
        "Website": "https://www.google.com/search?q=%E5%A4%A7%E5%A4%A9%E5%90%8E%E5%AE%AE",
        "StartTime": "17:35",
        "EndTime": "18:35",
        "Rating": 4.4,
        "Cost": 0,
        "WalkingLoad": 4,
        "InfoLoad": 6,
        "CrowdLevel": 6,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "汽車",
        "Distance": "2.5 km",
        "Duration": "10 min",
        "Speed": "15 km/h",
        "Cost": 150
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "大東夜市",
        "Address": "台南市東區林森路一段276號",
        "Latitude": 22.9826126,
        "Longitude": 120.2192395,
        "SpotType": [
          "夜市",
          "美食",
          "購物"
        ],
        "Description": "大東夜市是台南三大夜市之一，每週一、二、五營業，是品嚐台南特色小吃的好去處。從排隊名店到新奇攤位，應有盡有。在這裡可以盡情享受美食、玩遊戲、購物，體驗台南熱鬧的夜生活氛圍。",
        "Phone": "06-2301234",
        "Website": "https://www.google.com/search?q=%E5%A4%A7%E6%9D%B1%E5%A4%9C%E5%B8%82",
        "StartTime": "19:00",
        "EndTime": "21:00",
        "Rating": 4.1,
        "Cost": 300,
        "WalkingLoad": 8,
        "InfoLoad": 5,
        "CrowdLevel": 9,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 2,
        "TransportType": "汽車",
        "Distance": "2.5 km",
        "Duration": "10 min",
        "Speed": "15 km/h",
        "Cost": 150
      },
      {
        "DataType": "Spot",
        "Day": 2,
        "Date": "2026-02-13",
        "SpotName": "台南香格里拉遠東國際大飯店",
        "Address": "台南市東區大學路西段89號",
        "Latitude": 22.997,
        "Longitude": 120.2139,
        "SpotType": [
          "住宿"
        ],
        "Description": "結束充實的一天，返回舒適的飯店休息。台南香格里拉遠東國際大飯店提供寧靜的環境和優質的服務，讓旅客充分放鬆身心。為明天的旅程儲備能量，感受台南夜晚的寧靜與飯店的溫馨。",
        "Phone": "06-7028888",
        "Website": "https://www.shangri-la.com/tainan/fareasternplaza",
        "StartTime": "21:10",
        "EndTime": "24:00",
        "Rating": 4.6,
        "Cost": 3500,
        "WalkingLoad": 2,
        "InfoLoad": 2,
        "CrowdLevel": 4,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": false
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "台南香格里拉遠東國際大飯店",
        "Address": "台南市東區大學路西段89號",
        "Latitude": 22.997,
        "Longitude": 120.2139,
        "SpotType": [
          "住宿"
        ],
        "Description": "從飯店出發，準備開啟第三天的古蹟美食探索之旅。在飯店享受早餐，為一天的行程補充能量。飯店的地理位置優越，方便前往市區各個熱門景點，讓您的台南之旅更加便捷順暢。",
        "Phone": "06-7028888",
        "Website": "https://www.shangri-la.com/tainan/fareasternplaza",
        "StartTime": "00:00",
        "EndTime": "09:00",
        "Rating": 4.6,
        "Cost": 0,
        "WalkingLoad": 1,
        "InfoLoad": 1,
        "CrowdLevel": 3,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": false
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "汽車",
        "Distance": "1.8 km",
        "Duration": "7 min",
        "Speed": "15 km/h",
        "Cost": 120
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "神農街",
        "Address": "台南市中西區神農街",
        "Latitude": 22.9978123,
        "Longitude": 120.1959925,
        "SpotType": [
          "文化",
          "藝術",
          "古蹟"
        ],
        "Description": "神農街是台南保存最完整的老街之一，夜晚燈籠點亮時，更顯其迷人魅力。兩旁古老的街屋，許多已轉變為文創小店、咖啡館或民宿。漫步其中，感受時光倒流的氛圍，是體驗台南古樸與藝術氣息的好地方。",
        "Phone": "06-2312345",
        "Website": "https://www.google.com/search?q=%E7%A5%9E%E8%BE%B2%E8%A1%97",
        "StartTime": "09:15",
        "EndTime": "10:45",
        "Rating": 4.5,
        "Cost": 0,
        "WalkingLoad": 6,
        "InfoLoad": 6,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "步行",
        "Distance": "1.0 km",
        "Duration": "12 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "臺南市美術館1館",
        "Address": "台南市中西區南門路37號",
        "Latitude": 22.9913515,
        "Longitude": 120.2053538,
        "SpotType": [
          "藝術",
          "文化"
        ],
        "Description": "臺南市美術館1館由原臺南警察署古蹟改建，建築本身就是一件藝術品。其空間設計融合了古典與現代，展示著台灣與國際的藝術作品。在這裡可以享受藝術的薰陶，感受歷史建築的魅力，是文化愛好者不可錯過的地方。",
        "Phone": "06-2218881",
        "Website": "http://tnmfa.tainan.gov.tw/",
        "StartTime": "11:00",
        "EndTime": "12:30",
        "Rating": 4.6,
        "Cost": 200,
        "WalkingLoad": 5,
        "InfoLoad": 8,
        "CrowdLevel": 7,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "步行",
        "Distance": "0.5 km",
        "Duration": "6 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "阿江炒鱔魚",
        "Address": "台南市中西區民族路三段89號",
        "Latitude": 22.9983576,
        "Longitude": 120.1970408,
        "SpotType": [
          "美食"
        ],
        "Description": "阿江炒鱔魚是台南著名的老店，以其鑊氣十足的炒鱔魚意麵聞名。獨特的醬汁與鮮美的鱔魚，搭配Q彈的意麵，味道令人難忘。是品嚐台南在地特色小吃，挑戰味蕾的必訪之處，體驗府城庶民美食。",
        "Phone": "06-2223456",
        "Website": "https://www.google.com/search?q=%E9%98%BF%E6%B1%9F%E7%82%92%E9%B1%94%E9%AD%9A",
        "StartTime": "12:35",
        "EndTime": "13:35",
        "Rating": 4.3,
        "Cost": 150,
        "WalkingLoad": 1,
        "InfoLoad": 2,
        "CrowdLevel": 8,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "步行",
        "Distance": "0.7 km",
        "Duration": "9 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "延平郡王祠",
        "Address": "台南市中西區開山路152號",
        "Latitude": 22.9877958,
        "Longitude": 120.207623,
        "SpotType": [
          "古蹟",
          "宗教",
          "文化"
        ],
        "Description": "延平郡王祠是為了紀念鄭成功而建立的祠廟，環境清幽，綠樹成蔭。園區內有鄭成功文物館，展示其生平事蹟與相關文物。來此可以了解這位台灣歷史上的重要人物，感受其開疆闢土的精神與歷史意義。",
        "Phone": "06-2135518",
        "Website": "https://www.google.com/search?q=%E5%BB%B6%E5%B9%B3%E9%83%A1%E7%8E%8B%E7%A5%A0",
        "StartTime": "13:45",
        "EndTime": "15:00",
        "Rating": 4.4,
        "Cost": 0,
        "WalkingLoad": 5,
        "InfoLoad": 7,
        "CrowdLevel": 6,
        "IndoorOutdoor": "戶外",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "步行",
        "Distance": "0.5 km",
        "Duration": "6 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "台南司法博物館",
        "Address": "台南市中西區府前路一段307號",
        "Latitude": 23.127738,
        "Longitude": 120.2939283,
        "SpotType": [
          "文化",
          "古蹟"
        ],
        "Description": "台南司法博物館前身為日治時期的台南地方法院，建築外觀氣勢磅礴，內部裝潢精美。現在開放供民眾參觀，了解司法歷史與建築美學。其圓頂與華麗的構造吸引眾多遊客，是文化與歷史愛好者的絕佳去處。",
        "Phone": "06-2259999",
        "Website": "https://www.google.com/search?q=%E5%8F%B0%E5%8D%97%E5%8F%B8%E6%B3%95%E5%8D%9A%E7%89%A9%E9%A4%A8",
        "StartTime": "15:10",
        "EndTime": "16:30",
        "Rating": 4.5,
        "Cost": 0,
        "WalkingLoad": 4,
        "InfoLoad": 7,
        "CrowdLevel": 6,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "步行",
        "Distance": "0.5 km",
        "Duration": "6 min",
        "Speed": "5 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "義豐冬瓜茶 (總店)",
        "Address": "台南市中西區永福路二段212號",
        "Latitude": 22.9915499,
        "Longitude": 120.2125073,
        "SpotType": [
          "美食"
        ],
        "Description": "義豐冬瓜茶是台南知名的百年老店，以傳統古法熬製的冬瓜茶聞名。清甜解渴，風味獨特，深受在地人與遊客喜愛。炎炎夏日來一杯，清涼消暑，是體驗台南古早味飲品文化的好選擇。",
        "Phone": "06-2280000",
        "Website": "https://www.google.com/search?q=%E7%BE%A9%E8%B1%90%E5%86%AC%E7%93%9C%E8%8C%B6%20(%E7%B8%BD%E5%BA%97)",
        "StartTime": "16:35",
        "EndTime": "17:00",
        "Rating": 4.3,
        "Cost": 35,
        "WalkingLoad": 1,
        "InfoLoad": 2,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": true
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "步行",
        "Distance": "0.1 km",
        "Duration": "1 min",
        "Speed": "3 km/h",
        "Cost": 0
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "石精臼蚵仔煎",
        "Address": "台南市中西區民族路二段284巷33號",
        "Latitude": 22.9972,
        "Longitude": 120.2016,
        "SpotType": [
          "美食"
        ],
        "Description": "石精臼蚵仔煎是台南夜市小吃的代表之一，以其份量十足、蚵仔新鮮、煎得香酥的蚵仔煎聞名。搭配特製醬汁，味道鮮美。是體驗台南道地小吃文化的最佳選擇，品嚐府城獨特的街頭風味。",
        "Phone": "06-2291111",
        "Website": "https://www.google.com/search?q=%E7%9F%B3%E7%B2%BE%E8%87%BC%E8%9A%B5%E4%BB%94%E7%85%8E",
        "StartTime": "17:30",
        "EndTime": "18:30",
        "Rating": 4,
        "Cost": 100,
        "WalkingLoad": 1,
        "InfoLoad": 2,
        "CrowdLevel": 7,
        "IndoorOutdoor": "半開放",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": false
      },
      {
        "DataType": "Transport",
        "Day": 3,
        "TransportType": "汽車",
        "Distance": "1.5 km",
        "Duration": "7 min",
        "Speed": "15 km/h",
        "Cost": 120
      },
      {
        "DataType": "Spot",
        "Day": 3,
        "Date": "2026-02-14",
        "SpotName": "台南香格里拉遠東國際大飯店",
        "Address": "台南市東區大學路西段89號",
        "Latitude": 22.997,
        "Longitude": 120.2139,
        "SpotType": [
          "住宿"
        ],
        "Description": "旅程的最後一晚，回到溫馨舒適的飯店。台南香格里拉遠東國際大飯店為您的古蹟美食之旅畫下完美的句點。享受一夜好眠，回味這三天在台南的美好時光，並為隔天的離開做好準備。",
        "Phone": "06-7028888",
        "Website": "https://www.shangri-la.com/tainan/fareasternplaza",
        "StartTime": "18:40",
        "EndTime": "24:00",
        "Rating": 4.6,
        "Cost": 3500,
        "WalkingLoad": 2,
        "InfoLoad": 2,
        "CrowdLevel": 4,
        "IndoorOutdoor": "室內",
        "WeatherType": "晴到多雲",
        "Temperature": 22,
        "IsRealCoordinate": false
      }
    ]
  }
];

export const ITINERARY_DATA = ALL_ITINERARIES[0];
